### ISSUE TITLE
Add baseline correction for XRD

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eln.epfl.ch#60] opened 2020-09-03 20:55 UTC
Other software proposes the following algorithms

http://www.ba.ic.cnr.it/softwareic/qualx/data-reduction/background/

**Comment by kjappelbaum** [comment] 2020-09-04 04:52
Closed as it is duplicate of https://github.com/cheminfo/eln.epfl.ch/issues/43

**Closed by kjappelbaum** 2020-09-04 04:52 UTC
Labels: XRD
