### ISSUE TITLE
make IR view consistent with the newer ones

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#232] opened 2021-02-08 09:07 UTC
I think it would be nice if the views for all spectra types would be relatively consistent. When #230 is done it might make sense to also refactor the other views to use the same structure.

**Comment by lpatiny** [comment] 2021-02-08 12:55
Duplicate of https://github.com/cheminfo/eln.epfl.ch/issues/188

**Closed by lpatiny** 2021-02-08 12:55 UTC
